trigger:
- master
- refs/tags/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: cargo test --release --all
    displayName: 'Run tests'
  - script: cargo build --release
    displayName: 'Build artifacts'
  - script: |
      cp target/release/kulupu target/release/kulupu-linux
      shasum -a 256 target/release/kulupu-linux > target/release/kulupu-linux.sha256
    displayName: 'Finalize artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'target/release'
      contents: 'kulupu-linux*'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  timeoutInMinutes: 0
  steps:
  - script: git submodule update --init --recursive
    displayName: 'Submodules'
  - script: ./scripts/ci-init.sh
    displayName: 'Rust setup'
  - script: |
      source ~/.cargo/env
      cargo test --release --all
    displayName: 'Run tests'
  - script: |
      source ~/.cargo/env
      cargo build --release
    displayName: 'Build artifacts'
  - script: |
      cp target/release/kulupu target/release/kulupu-macos
      shasum -a 256 target/release/kulupu-macos > target/release/kulupu-macos.sha256
    displayName: 'Finalize artifacts'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'target/release'
      contents: 'kulupu-macos*'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
