[package]
name = "kulupu"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "kulupu"
path = "src/main.rs"

[dependencies]
derive_more = "0.14.0"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sr-io = { path = "vendor/substrate/core/sr-io" }
substrate-cli = { path = "vendor/substrate/core/cli" }
primitives = { package = "substrate-primitives", path = "vendor/substrate/core/primitives" }
substrate-executor = { path = "vendor/substrate/core/executor" }
substrate-service = { path = "vendor/substrate/core/service" }
inherents = { package = "substrate-inherents", path = "vendor/substrate/core/inherents" }
transaction-pool = { package = "substrate-transaction-pool", path = "vendor/substrate/core/transaction-pool" }
network = { package = "substrate-network", path = "vendor/substrate/core/network" }
substrate-client = { path = "vendor/substrate/core/client" }
basic-authorship = { package = "substrate-basic-authorship", path = "vendor/substrate/core/basic-authorship" }
kulupu-runtime = { path = "runtime" }
kulupu-primitives = { path = "primitives" }
consensus-pow = { package = "substrate-consensus-pow", path = "vendor/substrate/core/consensus/pow" }
kulupu-pow = { path = "pow" }
srml-timestamp = { path = "vendor/substrate/srml/timestamp" }
srml-system = { path = "vendor/substrate/srml/system" }
srml-anyupgrade = { path = "anyupgrade" }
srml-rewards = { path = "rewards" }
structopt = "0.2"
consensus-common = { package = "substrate-consensus-common", path = "vendor/substrate/core/consensus/common" }
serde_json = "1.0"
jsonrpc-core = "14.0.3"
jsonrpc-pubsub = "14.0.3"
jsonrpc-ws-server = "14.0.3"
hex = "0.3"

[build-dependencies]
vergen = "3"

[workspace]
members = [
	"runtime",
	"pow",
	"anyupgrade",
	"rewards",
]
exclude = ["vendor"]
