[package]
name = "kulupu"
version = "0.2.0"
authors = ["Wei Tang <hi@that.world>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "kulupu"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1", features = ["termination"] }
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sr-io = { path = "vendor/substrate/primitives/sr-io" }
substrate-cli = { path = "vendor/substrate/client/cli" }
primitives = { package = "substrate-primitives", path = "vendor/substrate/primitives/core" }
substrate-executor = { path = "vendor/substrate/client/executor" }
substrate-service = { path = "vendor/substrate/client/service" }
inherents = { package = "substrate-inherents", path = "vendor/substrate/primitives/inherents" }
transaction-pool = { package = "substrate-transaction-pool", path = "vendor/substrate/client/transaction-pool" }
network = { package = "substrate-network", path = "vendor/substrate/client/network" }
substrate-client = { path = "vendor/substrate/client" }
basic-authorship = { package = "substrate-basic-authorship", path = "vendor/substrate/client/basic-authorship" }
kulupu-runtime = { path = "runtime" }
kulupu-primitives = { path = "primitives" }
consensus-pow = { package = "substrate-consensus-pow", path = "vendor/substrate/client/consensus/pow" }
kulupu-pow = { path = "pow" }
pallet-timestamp = { path = "vendor/substrate/frame/timestamp" }
timestamp-primitives = { package = "sp-timestamp", path = "vendor/substrate/primitives/timestamp" }
frame-system = { path = "vendor/substrate/frame/system" }
pallet-anyupgrade = { path = "anyupgrade" }
pallet-rewards = { path = "rewards" }
structopt = "0.3"
consensus-common = { package = "substrate-consensus-common", path = "vendor/substrate/primitives/consensus/common" }
serde_json = "1.0"
jsonrpc-core = "14.0.3"
jsonrpc-pubsub = "14.0.3"
jsonrpc-ws-server = "14.0.3"
hex = "0.3"

[build-dependencies]
vergen = "3"

[workspace]
members = [
	"runtime",
	"pow",
	"anyupgrade",
	"rewards",
]
exclude = ["vendor"]
